Import Ambr parser code
JBEI/edd pull request #27
Opened 2021-10-07 05:28 UTC by somtirtharoy

2021-10-07 21:13 UTC, wmorrell requested changes

2021-10-07 21:13 UTC, wmorrell commented on server/edd/load/migrations/0004_auto_20211005_0854.py
> +# Generated by Django 3.2.7 on 2021-10-05 15:54
Please update to include only one migration for the changes in the PR. The best way to do this is to:
1. run `python manage.py migrate load 0002_builtin_bootstrap` to roll back the existing migrations;
2. delete the migration files added here;
3. run `python manage.py makemigrations --name defaultunit load` to re-generate a single migration in the final model state;

2021-10-07 21:13 UTC, wmorrell commented on server/edd/load/models.py
> +    edd_type_name = VarCharField(
This should be a `ForeignKey` field to the actual type to use.

2021-10-07 21:13 UTC, wmorrell commented on server/edd/load/parsers/core.py
> +        du_obj = DefaultUnit.objects.all()
This is loading everything in this table into memory. This mapper should only load in the `DefaultUnit` instances that will apply to the current mapping operation, by doing a lookup based on having a matching `Protocol` (or the `DefaultUnit` specifying a blank/`None` `Protocol`), matching parser class (or the parser class specifying blank/`None`), and matching `MeasurementType`.

2021-10-07 21:13 UTC, wmorrell commented on server/edd/load/parsers/core.py
> +        mtype_obj = MeasurementNameTransform.objects.all()
Same as above, this is loading everything in the table into memory. Do a lookup with the specific names used, as they are used. This should probably also have a `Protocol` to constrain the results, as different reactor setups may export different names for the same things depending on how the operator(s) have set up the Ambr. Constraining by parser used should be included as well.

2021-10-07 21:13 UTC, wmorrell commented on server/edd/load/tests/factory.py
> +class MeasurementTypeFactory(factory.django.DjangoModelFactory):
There's already a `MeasurementTypeFactory` in `main.tests.factory`, should use that one instead, or document a justification for having a separate one here.

2021-10-07 21:13 UTC, wmorrell commented on server/edd/load/tests/factory.py
> +class MeasurementUnitFactory(factory.django.DjangoModelFactory):
Same here, there's already a `UnitFactory` in `main.tests.factory`.

2021-10-07 21:13 UTC, wmorrell commented on server/edd/load/tests/factory.py
> +    measurement_type = factory.SubFactory(LayoutFactory)
The subfactory here should be `MeasurementTypeFactory`, not `LayoutFactory`.

2021-10-07 21:13 UTC, wmorrell commented on server/edd/load/tests/factory.py
> +    unit = factory.SubFactory(LayoutFactory)
The subfactory here should be `UnitFactory`, not `LayoutFactory`.

2021-10-07 21:13 UTC, wmorrell commented on server/main/migrations/0002_defaultunit.py
> +# Generated by Django 2.2.23 on 2021-09-22 14:41
This migration file should not exist; the models are in `edd.load` app now, not in `main` app.

2021-10-07 21:13 UTC, wmorrell commented on server/main/migrations/0003_delete_defaultunit.py
> +# Generated by Django 3.2.7 on 2021-10-05 15:46
This migration file should not exist, either. Steps are similar to fixing the migrations for `edd.load` app:
1. run `python manage.py migrate main 0001_edd_2_7` to roll back;
2. delete these files and update commits to remove them from the pull request;

2021-10-07 23:15 UTC, somtirtharoy commented
I am on it. Will get this to you tonight! Thanks so much!

On Thu, Oct 7, 2021 at 2:13 PM wmorrell ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In server/edd/load/migrations/0004_auto_20211005_0854.py
> <https://github.com/JBEI/edd/pull/27#discussion_r724493084>:
>
> > @@ -0,0 +1,31 @@
> +# Generated by Django 3.2.7 on 2021-10-05 15:54
>
> Please update to include only one migration for the changes in the PR. The
> best way to do this is to:
>
>    1. run python manage.py migrate load 0002_builtin_bootstrap to roll
>    back the existing migrations;
>    2. delete the migration files added here;
>    3. run python manage.py makemigrations --name defaultunit load to
>    re-generate a single migration in the final model state;
>
> ------------------------------
>
> In server/edd/load/models.py
> <https://github.com/JBEI/edd/pull/27#discussion_r724494363>:
>
> > +            "id": self.pk,
> +            "type_name": self.measurement_type.type_name,
> +            "unit_name": self.unit.unit_name,
> +        }
> +
> +
> +class MeasurementNameTransform(models.Model):
> +    class Meta:
> +        db_table = "measurement_name_transform"
> +
> +    input_type_name = VarCharField(
> +        help_text=_("Name of this Measurement Type in input."),
> +        verbose_name=_("Input Measurement Type"),
> +    )
> +
> +    edd_type_name = VarCharField(
>
> This should be a ForeignKey field to the actual type to use.
> ------------------------------
>
> In server/edd/load/parsers/core.py
> <https://github.com/JBEI/edd/pull/27#discussion_r724519152>:
>
> > +
> +class MeasurementMapper:
> +
> +    loa_name: str
> +    df: pd.DataFrame
> +    units: Dict
> +    mes_unit_map: Dict
> +    mtype_map = Dict
> +
> +    def __init__(self, name=None, df=None):
> +        self.loa_name = name
> +        self.df = df
> +
> +        # get the default units for measurements from the database
> +        self.mes_unit_map = {}
> +        du_obj = DefaultUnit.objects.all()
>
> This is loading everything in this table into memory. This mapper should
> only load in the DefaultUnit instances that will apply to the current
> mapping operation, by doing a lookup based on having a matching Protocol
> (or the DefaultUnit specifying a blank/None Protocol), matching parser
> class (or the parser class specifying blank/None), and matching
> MeasurementType.
> ------------------------------
>
> In server/edd/load/parsers/core.py
> <https://github.com/JBEI/edd/pull/27#discussion_r724525528>:
>
> > +    mtype_map = Dict
> +
> +    def __init__(self, name=None, df=None):
> +        self.loa_name = name
> +        self.df = df
> +
> +        # get the default units for measurements from the database
> +        self.mes_unit_map = {}
> +        du_obj = DefaultUnit.objects.all()
> +        for obj in du_obj:
> +            self.mes_unit_map[obj.measurement_type.type_name] = obj.unit.unit_name
> +
> +        # get the mapping between input measurement type names and expected
> +        # edd measurement type names from database
> +        self.mtype_map = {}
> +        mtype_obj = MeasurementNameTransform.objects.all()
>
> Same as above, this is loading everything in the table into memory. Do a
> lookup with the specific names used, as they are used. This should probably
> also have a Protocol to constrain the results, as different reactor
> setups may export different names for the same things depending on how the
> operator(s) have set up the Ambr. Constraining by parser used should be
> included as well.
> ------------------------------
>
> In server/edd/load/tests/factory.py
> <https://github.com/JBEI/edd/pull/27#discussion_r724527326>:
>
> > @@ -52,3 +54,35 @@ class Meta:
>
>      layout = factory.SubFactory(LayoutFactory)
>      mime_type = factory.Faker("mime_type")
> +
> +
> +class MeasurementTypeFactory(factory.django.DjangoModelFactory):
>
> There's already a MeasurementTypeFactory in main.tests.factory, should
> use that one instead, or document a justification for having a separate one
> here.
> ------------------------------
>
> In server/edd/load/tests/factory.py
> <https://github.com/JBEI/edd/pull/27#discussion_r724527830>:
>
> > @@ -52,3 +54,35 @@ class Meta:
>
>      layout = factory.SubFactory(LayoutFactory)
>      mime_type = factory.Faker("mime_type")
> +
> +
> +class MeasurementTypeFactory(factory.django.DjangoModelFactory):
> +    class Meta:
> +        model = main_models.MeasurementType
> +        django_get_or_create = ("type_name",)
> +
> +    type_name = ""
> +
> +
> +class MeasurementUnitFactory(factory.django.DjangoModelFactory):
>
> Same here, there's already a UnitFactory in main.tests.factory.
> ------------------------------
>
> In server/edd/load/tests/factory.py
> <https://github.com/JBEI/edd/pull/27#discussion_r724528491>:
>
> > +    type_name = ""
> +
> +
> +class MeasurementUnitFactory(factory.django.DjangoModelFactory):
> +    class Meta:
> +        model = main_models.MeasurementUnit
> +        django_get_or_create = ("unit_name",)
> +
> +    unit_name = ""
> +
> +
> +class DefaultUnitFactory(factory.django.DjangoModelFactory):
> +    class Meta:
> +        model = models.DefaultUnit
> +
> +    measurement_type = factory.SubFactory(LayoutFactory)
>
> The subfactory here should be MeasurementTypeFactory, not LayoutFactory.
> ------------------------------
>
> In server/edd/load/tests/factory.py
> <https://github.com/JBEI/edd/pull/27#discussion_r724529564>:
>
> > +
> +
> +class MeasurementUnitFactory(factory.django.DjangoModelFactory):
> +    class Meta:
> +        model = main_models.MeasurementUnit
> +        django_get_or_create = ("unit_name",)
> +
> +    unit_name = ""
> +
> +
> +class DefaultUnitFactory(factory.django.DjangoModelFactory):
> +    class Meta:
> +        model = models.DefaultUnit
> +
> +    measurement_type = factory.SubFactory(LayoutFactory)
> +    unit = factory.SubFactory(LayoutFactory)
>
> The subfactory here should be UnitFactory, not LayoutFactory.
> ------------------------------
>
> In server/main/migrations/0002_defaultunit.py
> <https://github.com/JBEI/edd/pull/27#discussion_r724530385>:
>
> > @@ -0,0 +1,55 @@
> +# Generated by Django 2.2.23 on 2021-09-22 14:41
>
> This migration file should not exist; the models are in edd.load app now,
> not in main app.
> ------------------------------
>
> In server/main/migrations/0003_delete_defaultunit.py
> <https://github.com/JBEI/edd/pull/27#discussion_r724530733>:
>
> > @@ -0,0 +1,14 @@
> +# Generated by Django 3.2.7 on 2021-10-05 15:46
>
> This migration file should not exist, either. Steps are similar to fixing
> the migrations for edd.load app:
>
>    1. run python manage.py migrate main 0001_edd_2_7 to roll back;
>    2. delete these files and update commits to remove them from the pull
>    request;
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/JBEI/edd/pull/27#pullrequestreview-774338440>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AKDGPCAB7AOICFQOVYTZU7LUFYEPNANCNFSM5FQNBYZQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-10-08 22:07 UTC, somtirtharoy commented on server/edd/load/migrations/0004_auto_20211005_0854.py
> +# Generated by Django 3.2.7 on 2021-10-05 15:54
Done

2021-10-08 22:07 UTC, somtirtharoy commented on server/edd/load/models.py
> +    edd_type_name = VarCharField(
this is a mapping between types so I want to keep this as a text field for the moment. I want to introduce this later with further improvements.

2021-10-08 22:08 UTC, somtirtharoy commented on server/edd/load/parsers/core.py
> +        du_obj = DefaultUnit.objects.all()
Done

2021-10-08 22:08 UTC, somtirtharoy commented on server/edd/load/parsers/core.py
> +        mtype_obj = MeasurementNameTransform.objects.all()
Done

2021-10-08 22:08 UTC, somtirtharoy commented on server/edd/load/tests/factory.py
> +class MeasurementTypeFactory(factory.django.DjangoModelFactory):
Done

2021-10-08 22:08 UTC, somtirtharoy commented on server/edd/load/tests/factory.py
> +class MeasurementUnitFactory(factory.django.DjangoModelFactory):
Done

2021-10-08 22:08 UTC, somtirtharoy commented on server/edd/load/tests/factory.py
> +    measurement_type = factory.SubFactory(LayoutFactory)
Done

2021-10-08 22:08 UTC, somtirtharoy commented on server/edd/load/tests/factory.py
> +    unit = factory.SubFactory(LayoutFactory)
Done

2021-10-08 22:08 UTC, somtirtharoy commented on server/main/migrations/0002_defaultunit.py
> +# Generated by Django 2.2.23 on 2021-09-22 14:41
Done

2021-10-08 22:08 UTC, somtirtharoy commented on server/main/migrations/0003_delete_defaultunit.py
> +# Generated by Django 3.2.7 on 2021-10-05 15:46
Done

2021-10-08 22:09 UTC, somtirtharoy commented
I pushed the changes, please check.

On Thu, Oct 7, 2021 at 4:15 PM Somtirtha Roy ***@***.***> wrote:

> I am on it. Will get this to you tonight! Thanks so much!
>
> On Thu, Oct 7, 2021 at 2:13 PM wmorrell ***@***.***> wrote:
>
>> ***@***.**** requested changes on this pull request.
>> ------------------------------
>>
>> In server/edd/load/migrations/0004_auto_20211005_0854.py
>> <https://github.com/JBEI/edd/pull/27#discussion_r724493084>:
>>
>> > @@ -0,0 +1,31 @@
>> +# Generated by Django 3.2.7 on 2021-10-05 15:54
>>
>> Please update to include only one migration for the changes in the PR.
>> The best way to do this is to:
>>
>>    1. run python manage.py migrate load 0002_builtin_bootstrap to roll
>>    back the existing migrations;
>>    2. delete the migration files added here;
>>    3. run python manage.py makemigrations --name defaultunit load to
>>    re-generate a single migration in the final model state;
>>
>> ------------------------------
>>
>> In server/edd/load/models.py
>> <https://github.com/JBEI/edd/pull/27#discussion_r724494363>:
>>
>> > +            "id": self.pk,
>> +            "type_name": self.measurement_type.type_name,
>> +            "unit_name": self.unit.unit_name,
>> +        }
>> +
>> +
>> +class MeasurementNameTransform(models.Model):
>> +    class Meta:
>> +        db_table = "measurement_name_transform"
>> +
>> +    input_type_name = VarCharField(
>> +        help_text=_("Name of this Measurement Type in input."),
>> +        verbose_name=_("Input Measurement Type"),
>> +    )
>> +
>> +    edd_type_name = VarCharField(
>>
>> This should be a ForeignKey field to the actual type to use.
>> ------------------------------
>>
>> In server/edd/load/parsers/core.py
>> <https://github.com/JBEI/edd/pull/27#discussion_r724519152>:
>>
>> > +
>> +class MeasurementMapper:
>> +
>> +    loa_name: str
>> +    df: pd.DataFrame
>> +    units: Dict
>> +    mes_unit_map: Dict
>> +    mtype_map = Dict
>> +
>> +    def __init__(self, name=None, df=None):
>> +        self.loa_name = name
>> +        self.df = df
>> +
>> +        # get the default units for measurements from the database
>> +        self.mes_unit_map = {}
>> +        du_obj = DefaultUnit.objects.all()
>>
>> This is loading everything in this table into memory. This mapper should
>> only load in the DefaultUnit instances that will apply to the current
>> mapping operation, by doing a lookup based on having a matching Protocol
>> (or the DefaultUnit specifying a blank/None Protocol), matching parser
>> class (or the parser class specifying blank/None), and matching
>> MeasurementType.
>> ------------------------------
>>
>> In server/edd/load/parsers/core.py
>> <https://github.com/JBEI/edd/pull/27#discussion_r724525528>:
>>
>> > +    mtype_map = Dict
>> +
>> +    def __init__(self, name=None, df=None):
>> +        self.loa_name = name
>> +        self.df = df
>> +
>> +        # get the default units for measurements from the database
>> +        self.mes_unit_map = {}
>> +        du_obj = DefaultUnit.objects.all()
>> +        for obj in du_obj:
>> +            self.mes_unit_map[obj.measurement_type.type_name] = obj.unit.unit_name
>> +
>> +        # get the mapping between input measurement type names and expected
>> +        # edd measurement type names from database
>> +        self.mtype_map = {}
>> +        mtype_obj = MeasurementNameTransform.objects.all()
>>
>> Same as above, this is loading everything in the table into memory. Do a
>> lookup with the specific names used, as they are used. This should probably
>> also have a Protocol to constrain the results, as different reactor
>> setups may export different names for the same things depending on how the
>> operator(s) have set up the Ambr. Constraining by parser used should be
>> included as well.
>> ------------------------------
>>
>> In server/edd/load/tests/factory.py
>> <https://github.com/JBEI/edd/pull/27#discussion_r724527326>:
>>
>> > @@ -52,3 +54,35 @@ class Meta:
>>
>>      layout = factory.SubFactory(LayoutFactory)
>>      mime_type = factory.Faker("mime_type")
>> +
>> +
>> +class MeasurementTypeFactory(factory.django.DjangoModelFactory):
>>
>> There's already a MeasurementTypeFactory in main.tests.factory, should
>> use that one instead, or document a justification for having a separate one
>> here.
>> ------------------------------
>>
>> In server/edd/load/tests/factory.py
>> <https://github.com/JBEI/edd/pull/27#discussion_r724527830>:
>>
>> > @@ -52,3 +54,35 @@ class Meta:
>>
>>      layout = factory.SubFactory(LayoutFactory)
>>      mime_type = factory.Faker("mime_type")
>> +
>> +
>> +class MeasurementTypeFactory(factory.django.DjangoModelFactory):
>> +    class Meta:
>> +        model = main_models.MeasurementType
>> +        django_get_or_create = ("type_name",)
>> +
>> +    type_name = ""
>> +
>> +
>> +class MeasurementUnitFactory(factory.django.DjangoModelFactory):
>>
>> Same here, there's already a UnitFactory in main.tests.factory.
>> ------------------------------
>>
>> In server/edd/load/tests/factory.py
>> <https://github.com/JBEI/edd/pull/27#discussion_r724528491>:
>>
>> > +    type_name = ""
>> +
>> +
>> +class MeasurementUnitFactory(factory.django.DjangoModelFactory):
>> +    class Meta:
>> +        model = main_models.MeasurementUnit
>> +        django_get_or_create = ("unit_name",)
>> +
>> +    unit_name = ""
>> +
>> +
>> +class DefaultUnitFactory(factory.django.DjangoModelFactory):
>> +    class Meta:
>> +        model = models.DefaultUnit
>> +
>> +    measurement_type = factory.SubFactory(LayoutFactory)
>>
>> The subfactory here should be MeasurementTypeFactory, not LayoutFactory.
>> ------------------------------
>>
>> In server/edd/load/tests/factory.py
>> <https://github.com/JBEI/edd/pull/27#discussion_r724529564>:
>>
>> > +
>> +
>> +class MeasurementUnitFactory(factory.django.DjangoModelFactory):
>> +    class Meta:
>> +        model = main_models.MeasurementUnit
>> +        django_get_or_create = ("unit_name",)
>> +
>> +    unit_name = ""
>> +
>> +
>> +class DefaultUnitFactory(factory.django.DjangoModelFactory):
>> +    class Meta:
>> +        model = models.DefaultUnit
>> +
>> +    measurement_type = factory.SubFactory(LayoutFactory)
>> +    unit = factory.SubFactory(LayoutFactory)
>>
>> The subfactory here should be UnitFactory, not LayoutFactory.
>> ------------------------------
>>
>> In server/main/migrations/0002_defaultunit.py
>> <https://github.com/JBEI/edd/pull/27#discussion_r724530385>:
>>
>> > @@ -0,0 +1,55 @@
>> +# Generated by Django 2.2.23 on 2021-09-22 14:41
>>
>> This migration file should not exist; the models are in edd.load app
>> now, not in main app.
>> ------------------------------
>>
>> In server/main/migrations/0003_delete_defaultunit.py
>> <https://github.com/JBEI/edd/pull/27#discussion_r724530733>:
>>
>> > @@ -0,0 +1,14 @@
>> +# Generated by Django 3.2.7 on 2021-10-05 15:46
>>
>> This migration file should not exist, either. Steps are similar to fixing
>> the migrations for edd.load app:
>>
>>    1. run python manage.py migrate main 0001_edd_2_7 to roll back;
>>    2. delete these files and update commits to remove them from the pull
>>    request;
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/JBEI/edd/pull/27#pullrequestreview-774338440>, or
>> unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/AKDGPCAB7AOICFQOVYTZU7LUFYEPNANCNFSM5FQNBYZQ>
>> .
>> Triage notifications on the go with GitHub Mobile for iOS
>> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
>> or Android
>> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>>
>>
>

2021-10-12 22:23 UTC, wmorrell requested changes

2021-10-12 22:23 UTC, wmorrell commented on docker/edd/core/Pipfile.lock
> +        "numpy": {
The lock file here is re-installing `numpy` over top of the version that's already installed in the base `scikit-learn` image. I believe this is because of adding `pandas`. You should not need to include `pandas` at all and change the installed packages relative to what's already in trunk.

2021-10-12 22:23 UTC, wmorrell commented on server/edd/load/migrations/0002_builtin_bootstrap.py
> +    LAYOUT_AMBR = Layout.objects.create(name="Ambr", description="")
Since you're adding models and generating a new migration anyway, the bootstrap for the new parser should go in with the new migration `0003_defaultunit` instead of editing this one and manually inserting into existing deployments.

2021-10-12 22:23 UTC, wmorrell commented on server/edd/load/models.py
> +    edd_type_name = VarCharField(
Changing data models involves doing migrations, and excessive migration churn quickly becomes a problem in projects. Get the data model right up-front, because getting it wrong initially makes everything harder down the line. This needs to be a `ForeignKey` to the actual type. Don't just leave everything as strings.

2021-10-12 22:23 UTC, wmorrell commented on server/edd/load/parsers/core.py
> +class MultiSheetExcelParserMixin:
This class is still doing too much. The functionality of the `MeasurementMapper`, selecting pairs of columns, etc. needs to be in `AmbrExcelParser`. A parser that's dealing with multiple Excel sheets should *only* be dealing with looping over all sheets, and calling a function to process the rows for each one. Thus, the `parse(file)` function should look something like this:

```python
def parse(self, file):
    wb = load_workbook(file, read_only=True, data_only=True)
    for ws in wb.worksheets:
        self._parse_sheet_rows(ws)
    return self._parse_result
```

It's then the responsibility for any classes using `MultiSheetExcelParserMixin` (including `AmbrExcelParser`) to define a `_parse_sheet_rows(self, ws)` method that will process the sheet, and a `_parse_result` property that takes all the collected info from all the sheets processed, and returns a `ParseResult` instance.

2021-10-12 22:23 UTC, wmorrell commented on server/edd/load/parsers/generic.py
> +
Make sure you have `pre-commit` set up to run. These empty lines should have been deleted by the repo's hooks.

2021-10-12 22:23 UTC, wmorrell commented on server/edd/load/tests/test_ambr_parser.py
> +@pytest.mark.django_db
The `pytest.mark.django_db` annotation is for marking tests. It has no function for items not called by `pytest`. See: https://pytest-django.readthedocs.io/en/latest/helpers.html#pytest.mark.django_db

2021-11-04 04:51 UTC, closed without merging